### ISSUE TITLE
Shows dirt screen for a sec connecting to server

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Minenash/Seamless-Loading-Screen#11]
https://user-images.githubusercontent.com/618276/105563310-7aea6000-5cd2-11eb-9b49-ecf71db153f5.mp4

**Comment by Minenash** [comment]
Which version are you using?

**Comment by supersaiyansubtlety** [comment]
`seamless-loading-screen-1.1.0+1.16`

**Comment by Minenash** [comment]
When I get home, I'll see if I can reproduce it

**Comment by Minenash** [comment]
Hmm, does this error happen if you join when you're in the overworld?

**Comment by supersaiyansubtlety** [comment]
It does. 

I also asked my fried who's using the same mod set on the server, and they're actually not getting it...

**Comment by Minenash** [comment]
Did it ever resolve itself and/or have you tried it with no other mods installed?

**Comment by supersaiyansubtlety** [comment]
Just finished a binary search, and the conflict is with [*Bag of Feathers*](https://github.com/JamiesWhiteShirt/bag-of-feathers) of all things....

Bag of Feathers has started causing new issues now too, I suspect because of the update to fapi 0.30.0. 

Without bag of Feathers, I get the typical crash that's been reported already and is caught by Not Enough Crashes when exiting a world. 

With Bag of Feathers, after exiting a world in singleplayer, my game goes from 

![2021-02-04_15 54 29](https://user-images.githubusercontent.com/618276/107133011-f8000280-6898-11eb-95f7-3b93cc865fe0.png)

to

![2021-02-06_15 51 46](https://user-images.githubusercontent.com/618276/107133013-fb938980-6898-11eb-80e7-b049b02cbe33.png)

This is in fullscreen, everything shifts down and there's black space filling the top. 

My cursor still needs to click the old (correct) button positions, even though this doesn't line up with the new button positions. 

If I try to leave a server, first I'm taken back to the disconnect screen with the same issues as above, but then if I try to disconnect a second time, minecraft freezes and I have to kill it. 

For now I'm just uninstalling Bag of Feathers since it seems like it's dong something it really shouldn't be doing...

**Comment by supersaiyansubtlety** [comment]
Apparently at least one other mod causes the dirt screen issue as well, but not the squashed screen nonsense. 

I can't binary search again right now, maybe tomorrow, or maybe the one conflicting mod is enough to pinpoint the issue.

**Comment by Minenash** [comment]
> I get the typical crash that's been reported already and is caught by Not Enough Crashes when exiting a world.
This was fixed in v1.2.0 (accidentally disabled in v1.2.1, but re-enabled in v1.2.2)

**Comment by supersaiyansubtlety** [comment]
Ah, I've since learned that some other mod is causing the same issue... I'll do more binary searches later...

**Comment by supersaiyansubtlety** [comment]
So it seems like a lot of different mods all cause the flash of dirt, so far I've found:
- ClassicalArt-1.16.4-1.0.0-fabric
- craftingpad-1.16.5-fabric0.30.0-1.0.5
- curios-fabric-0.0.11-1.16.4
Also it seems removing these mods from just the server is enough to fix the dirt flash.

**Comment by Lucipo** [comment]
Just wanted to respond saying that I also have this flashing bug with my modpack while connecting to servers

mod list:
https://www.curseforge.com/minecraft/modpacks/neoteric-vanilla

**Comment by Toon2400** [comment]
confirming this still happens in 1.18.2, it happens during the rendering of chunks stage

**Comment by Dragon-Seeker** [comment]
Should be fixed with the lastest rounds of rewrite
