### ISSUE TITLE
[Bug] Forge - Sodium incompatibility 1.19.2

### ISSUE THREAD

**Issue by DTech10** [Minenash/Seamless-Loading-Screen#77]
[Latest Logs](https://mclo.gs/dgyGZoY)
No crash logs

**Comment by Dragon-Seeker** [comment]
Such is an issue that is fixed with the Fabric Version due to the easy way of manipulating what mixins are on and off. Will need to investigate a compatibility method for Forge.

**Comment by Dragon-Seeker** [comment]
Seems that the Rubidium does have support for disabling mixins so I hope to release an update fixing such.

**Comment by Dragon-Seeker** [comment]
Due to this [line](https://github.com/Asek3/Rubidium/blob/8eaaabb4572852cbc5d476bfb2f5a00d131de23d/src/main/java/me/jellysquid/mods/sodium/common/config/SodiumConfig.java#L205) of code being commented out, I can't use the easy method of disabling the mixin within the toml until for 1.19.2. Such should work with 1.19.4 and 1.20 but 1.19.2 will require an update on their side to say the least

**Comment by DTech10** [comment]
Tested the new version, still doesnt work

[Latest Logs](https://mclo.gs/dxWyl4q)

``` java
[30Aug2023 12:15:56.673] [main/FATAL] [mixin/]: Mixin apply failed seamless_loading_screen-common.mixins.json:LevelLoadingScreenMixin -> net.minecraft.client.gui.screens.LevelLoadingScreen: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/client/gui/screens/LevelLoadingScreen::changeBackgroundColor with priority 1000 cannot inject into net/minecraft/client/gui/screens/LevelLoadingScreen::m_96149_(Lcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/server/level/progress/StoringChunkProgressListener;IIII)V merged by me.jellysquid.mods.sodium.mixin.features.gui.fast_loading_screen.MixinLevelLoadingScreen with priority 1000 [PREINJECT Applicator Phase -> seamless_loading_screen-common.mixins.json:LevelLoadingScreenMixin -> Prepare Injections ->  -> modify$egi000$changeBackgroundColor(I)I -> Prepare]
```

**Comment by Dragon-Seeker** [comment]
> Tested the new version, still doesnt work
> 
> [Latest Logs](https://mclo.gs/dxWyl4q)
> 
> ```java
> [30Aug2023 12:15:56.673] [main/FATAL] [mixin/]: Mixin apply failed seamless_loading_screen-common.mixins.json:LevelLoadingScreenMixin -> net.minecraft.client.gui.screens.LevelLoadingScreen: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on net/minecraft/client/gui/screens/LevelLoadingScreen::changeBackgroundColor with priority 1000 cannot inject into net/minecraft/client/gui/screens/LevelLoadingScreen::m_96149_(Lcom/mojang/blaze3d/vertex/PoseStack;Lnet/minecraft/server/level/progress/StoringChunkProgressListener;IIII)V merged by me.jellysquid.mods.sodium.mixin.features.gui.fast_loading_screen.MixinLevelLoadingScreen with priority 1000 [PREINJECT Applicator Phase -> seamless_loading_screen-common.mixins.json:LevelLoadingScreenMixin -> Prepare Injections ->  -> modify$egi000$changeBackgroundColor(I)I -> Prepare]
> ```

This can not be fixed until Rubidum backports the needed feature. Place `mixin.features.gui.fast_loading_screen=false` into the sodium-mixins.properties file under the config folder as a temp fix until the port gets working as this only applies for 1.19.2

**Comment by DTech10** [comment]
yes i did that, but i found a bug where when you leave the world it doesn't make a new screenshot

**Comment by Dragon-Seeker** [comment]
Send a log so I got something to go off due to this being a new issue

**Comment by DTech10** [comment]
this is the [Latest logs](https://mclo.gs/9mLA48T)

**Comment by Dragon-Seeker** [comment]
Due to the size of log file and the limit time for which to try and find the issue, I recommend making a new Issue and possibly narrowing the mod causing the issue. I am closing this issue as resolved with the first issue though.
