### ISSUE TITLE
[Bug] Incompatiblity with Wynntils

### ISSUE THREAD

**Issue by MenacingPerson** [Minenash/Seamless-Loading-Screen#86]
In v2.0.1, this was in the changelog:

- Add fallback for mods who do various screen stuff during loading

But actually, I have a mod which does exactly that, and it's not possible to click on the screen it pops up right after loading.

Before this update, it completely broke the game by not allowing me to click anything in the whole game, but this time I just can't click any button on the mod's screen and pressing esc fixes it. But it is still kind of broken, yeah.

The mod is wynntils

**Comment by Dragon-Seeker** [comment]
The above change was an attempt to fix screens like Fastload, Fastquit, and similar ones. Such is working but required another fallback for people who override our fade screen early leading to mouse input being canceled way after it should.

Such has may have been fixed with a recent addition for more failsafe like this which can be found within the [Actions](https://github.com/Minenash/Seamless-Loading-Screen/actions) if you want to test.

Next time when making a mod bug report, don't just blatantly assume that a fix will work as each mod does actions differently meaning it may not be known or be a different issue which it is. Moreover it is a good idea to include: 

- Effected Mod Version
- Minecraft Version
- Loader Type
- An image/recording of the issue if not directly a crash
- Log File
- ModList if no Log can be found

**Comment by Dragon-Seeker** [comment]
May be similar to #83

**Comment by MenacingPerson** [comment]
> Next time when making a mod bug report, don't just blatantly assume that a fix will work as each mod does actions differently meaning it may not be known or be a different issue which it is. Moreover it is a good idea to include:

I'm sorry, will keep in mind.

I will test the actions build and report back (it's 1.19.4 btw)

**Comment by Dragon-Seeker** [comment]
Have you tested if the given build fixed the issue?

**Comment by MenacingPerson** [comment]
Sorry. Got caught up in stuff and forgot to reply.

https://github.com/Minenash/Seamless-Loading-Screen/actions/runs/6078753512

This has exactly the same behaviour as the normal modrinth one, which is documented above. It's not fixed, sadly.

1.19.4 fabric 0.14.22, latest wynntils version

**Comment by MenacingPerson** [comment]
If it's of any help, here's the screen in question:

https://github.com/Wynntils/Artemis/blob/main/common/src/main/java/com/wynntils/screens/characterselector/CharacterSelectorScreen.java

**Comment by Dragon-Seeker** [comment]
Overall Wynntils API is disregarding both platforms it's using either Fabric or Forge. Their API seems quite unsafe based on its operations and frankly doesn't have an easy way of debugging what is going on. 

I would recommend opening an issue on their side as I believe this problem is not easily solved without a large amount of investigation.

**Comment by Dragon-Seeker** [comment]
The most likely solution is I will make a configured blacklist for this and automatically add such due to not having the time or energy as stated to investigate the issue.

**Comment by MenacingPerson** [comment]
Thank you for that. Blacklisting the server `*.wynncraft.com` would work, as that is where the mod itself activates. Wynncraft also doesn't benefit from seamless loading screen, even in vanilla, so the mod is useless there.

The reason I made this issue is because the Wynntils mod adds a separate button to launch wynncraft where you can't toggle this mod off. I was thinking this would be a simple fix and benefit other mods, so I made this issue, but now just blacklisting the wynncraft server works, I think.

If regex doesn't work in the blacklist then I think play.wynncraft.com is the IP that the wynntils button uses.

**Comment by Dragon-Seeker** [comment]
Such has been released in the latest version for 1.19.4 and up.
